#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    # Write your code here
    numberofswaps=0
    for i in range(1,len(a)):
        for j in range(len(a)-i):
            if a[j]>a[j+1]:
                aux=a[j]
                a[j]=a[j+1]
                a[j+1]=aux
                numberofswaps+=1
        if numberofswaps==0:
            break
    print(f"Array is sorted in {numberofswaps} swaps.")
    print(f"First Element: {a[0]}")
    print(f"Last Element: {a[-1]}")
        
