#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':

    arr = []
    m=-(sys.maxsize-1)
    for _ in range(6):
        arr.append(list(map(int, input().rstrip().split())))
    for i in range(4):
        for b in range(4):
            s=0
            for a in range(i,i+3):
                 s+=arr[b][a]
            s+=arr[b+1][i+1]
            for a in range(i,i+3):
                s+=arr[b+2][a]
            if s>m:
               m=s  
    print(m)   
